version: '3.8'

services:
  sigap:
    container_name: sigap-proxy
    build: .
    ports:
      - "4001:3000"
    environment:
      - TARGET_URL=${TARGET_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: always
